import type { MLBTeam, TeamCategory, TimelineEvent, QuickFact } from "@/lib/mlb-team-types";

/* ─── Reliable seeded placeholder images (picsum.photos always resolves) ─── */
const stadiumImg = (seed: string | number) =>
  `https://picsum.photos/seed/${seed}/800/450`;

/* ─── 30 MLB Teams Mock Data ─── */
const ALL_TEAMS: MLBTeam[] = [
  // ── American League East ──
  {
    id: "bal",
    slug: "baltimore-orioles",
    name: "Baltimore Orioles",
    city: "Baltimore",
    shortName: "BAL",
    primaryColor: "#df4601",
    accentColor: "#000000",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/bal/800/450",
    stadium: "Oriole Park at Camden Yards",
    stadiumCapacity: 45971,
    founded: 1901,
    championships: 3,
    league: "American",
    division: "East",
    description: "Baltimore's beloved Birds have called Camden Yards home since 1992, a park that revolutionized modern ballpark design.",
  },
  {
    id: "bos",
    slug: "boston-red-sox",
    name: "Boston Red Sox",
    city: "Boston",
    shortName: "BOS",
    primaryColor: "#bd3039",
    accentColor: "#0c2340",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/bos/800/450",
    stadium: "Fenway Park",
    stadiumCapacity: 37755,
    founded: 1901,
    championships: 9,
    league: "American",
    division: "East",
    description: "Baseball's oldest and most intimate park, Fenway Park has been the home of the Red Sox since 1912.",
  },
  {
    id: "nyy",
    slug: "new-york-yankees",
    name: "New York Yankees",
    city: "New York",
    shortName: "NYY",
    primaryColor: "#132448",
    accentColor: "#e5e7eb",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/nyy/800/450",
    stadium: "Yankee Stadium",
    stadiumCapacity: 54251,
    founded: 1901,
    championships: 27,
    league: "American",
    division: "East",
    description: "The most storied franchise in baseball history with 27 World Series championships and legends like Ruth, Gehrig, and Jeter.",
  },
  {
    id: "tb",
    slug: "tampa-bay-rays",
    name: "Tampa Bay Rays",
    city: "St. Petersburg",
    shortName: "TB",
    primaryColor: "#092c5c",
    accentColor: "#8fbce6",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/tb/800/450",
    stadium: "Tropicana Field",
    stadiumCapacity: 25000,
    founded: 1998,
    championships: 0,
    league: "American",
    division: "East",
    description: "A model franchise for analytics-driven baseball, the Rays consistently compete with one of MLB's lowest payrolls.",
  },
  {
    id: "tor",
    slug: "toronto-blue-jays",
    name: "Toronto Blue Jays",
    city: "Toronto",
    shortName: "TOR",
    primaryColor: "#134a8e",
    accentColor: "#e8291c",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/tor/800/450",
    stadium: "Rogers Centre",
    stadiumCapacity: 49286,
    founded: 1977,
    championships: 2,
    league: "American",
    division: "East",
    description: "Canada's only MLB team, the Blue Jays won back-to-back World Series titles in 1992 and 1993.",
  },
  // ── American League Central ──
  {
    id: "cws",
    slug: "chicago-white-sox",
    name: "Chicago White Sox",
    city: "Chicago",
    shortName: "CWS",
    primaryColor: "#27251f",
    accentColor: "#c4ced4",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/cws/800/450",
    stadium: "Guaranteed Rate Field",
    stadiumCapacity: 40615,
    founded: 1900,
    championships: 3,
    league: "American",
    division: "Central",
    description: "The South Side's team plays in one of baseball's most modernized ballparks and is building toward another championship run.",
  },
  {
    id: "cle",
    slug: "cleveland-guardians",
    name: "Cleveland Guardians",
    city: "Cleveland",
    shortName: "CLE",
    primaryColor: "#00385d",
    accentColor: "#e31937",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/cle/800/450",
    stadium: "Progressive Field",
    stadiumCapacity: 34830,
    founded: 1894,
    championships: 2,
    league: "American",
    division: "Central",
    description: "Formerly the Indians, Cleveland rebranded as the Guardians in 2022, representing the city's working-class spirit.",
  },
  {
    id: "det",
    slug: "detroit-tigers",
    name: "Detroit Tigers",
    city: "Detroit",
    shortName: "DET",
    primaryColor: "#0c2340",
    accentColor: "#fa4616",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/det/800/450",
    stadium: "Comerica Park",
    stadiumCapacity: 41083,
    founded: 1894,
    championships: 4,
    league: "American",
    division: "Central",
    description: "Motor City's beloved franchise plays in Comerica Park, known for its iconic tiger sculptures and fountain centerfield.",
  },
  {
    id: "kc",
    slug: "kansas-city-royals",
    name: "Kansas City Royals",
    city: "Kansas City",
    shortName: "KC",
    primaryColor: "#004687",
    accentColor: "#c09a5b",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/kc/800/450",
    stadium: "Kauffman Stadium",
    stadiumCapacity: 37903,
    founded: 1969,
    championships: 2,
    league: "American",
    division: "Central",
    description: "Two-time World Series champions, the Royals play in Kauffman Stadium, one of the sport's most beloved ballparks.",
  },
  {
    id: "min",
    slug: "minnesota-twins",
    name: "Minnesota Twins",
    city: "Minneapolis",
    shortName: "MIN",
    primaryColor: "#002b5c",
    accentColor: "#d31145",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/min/800/450",
    stadium: "Target Field",
    stadiumCapacity: 38544,
    founded: 1901,
    championships: 3,
    league: "American",
    division: "Central",
    description: "Target Field opened in 2010 and has become one of MLB's premier outdoor parks in a cold-weather city.",
  },
  // ── American League West ──
  {
    id: "hou",
    slug: "houston-astros",
    name: "Houston Astros",
    city: "Houston",
    shortName: "HOU",
    primaryColor: "#002d62",
    accentColor: "#eb6e1f",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/hou/800/450",
    stadium: "Minute Maid Park",
    stadiumCapacity: 41168,
    founded: 1962,
    championships: 2,
    league: "American",
    division: "West",
    description: "A powerhouse franchise with multiple World Series appearances, the Astros play in Minute Maid Park in downtown Houston.",
  },
  {
    id: "laa",
    slug: "los-angeles-angels",
    name: "Los Angeles Angels",
    city: "Anaheim",
    shortName: "LAA",
    primaryColor: "#ba0021",
    accentColor: "#003263",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/laa/800/450",
    stadium: "Angel Stadium",
    stadiumCapacity: 45957,
    founded: 1961,
    championships: 1,
    league: "American",
    division: "West",
    description: "Playing in one of MLB's oldest ballparks, Angel Stadium features the iconic rock formation with flowing waterfalls in centerfield.",
  },
  {
    id: "oak",
    slug: "athletics",
    name: "Athletics",
    city: "Sacramento",
    shortName: "OAK",
    primaryColor: "#003831",
    accentColor: "#efb21e",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/oak/800/450",
    stadium: "Sutter Health Park",
    stadiumCapacity: 14014,
    founded: 1901,
    championships: 9,
    league: "American",
    division: "West",
    description: "Nine-time World Series champions, the A's are in Sacramento temporarily while their new Las Vegas ballpark is constructed.",
  },
  {
    id: "sea",
    slug: "seattle-mariners",
    name: "Seattle Mariners",
    city: "Seattle",
    shortName: "SEA",
    primaryColor: "#0c2c56",
    accentColor: "#005c5c",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/sea/800/450",
    stadium: "T-Mobile Park",
    stadiumCapacity: 47929,
    founded: 1977,
    championships: 0,
    league: "American",
    division: "West",
    description: "T-Mobile Park is celebrated for its retractable roof, unique asymmetrical outfield dimensions, and breathtaking mountain views.",
  },
  {
    id: "tex",
    slug: "texas-rangers",
    name: "Texas Rangers",
    city: "Arlington",
    shortName: "TEX",
    primaryColor: "#003278",
    accentColor: "#c0111f",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/tex/800/450",
    stadium: "Globe Life Field",
    stadiumCapacity: 40518,
    founded: 1961,
    championships: 1,
    league: "American",
    division: "West",
    description: "2023 World Series champions, the Rangers play in Globe Life Field, a retractable-roof stadium opened in 2020.",
  },
  // ── National League East ──
  {
    id: "atl",
    slug: "atlanta-braves",
    name: "Atlanta Braves",
    city: "Atlanta",
    shortName: "ATL",
    primaryColor: "#13274f",
    accentColor: "#ce1141",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/atl/800/450",
    stadium: "Truist Park",
    stadiumCapacity: 41084,
    founded: 1876,
    championships: 4,
    league: "National",
    division: "East",
    description: "One of baseball's oldest franchises, the Braves are 2021 World Series champions playing in the Battery Atlanta complex.",
  },
  {
    id: "mia",
    slug: "miami-marlins",
    name: "Miami Marlins",
    city: "Miami",
    shortName: "MIA",
    primaryColor: "#00a3e0",
    accentColor: "#ef3340",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/mia/800/450",
    stadium: "loanDepot Park",
    stadiumCapacity: 36742,
    founded: 1993,
    championships: 2,
    league: "National",
    division: "East",
    description: "Despite a modest payroll, the Marlins have won two World Series titles (1997, 2003) with roster-wide team effort.",
  },
  {
    id: "nym",
    slug: "new-york-mets",
    name: "New York Mets",
    city: "New York",
    shortName: "NYM",
    primaryColor: "#002d72",
    accentColor: "#f97316",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/atl/800/450",
    stadium: "Citi Field",
    stadiumCapacity: 41922,
    founded: 1962,
    championships: 2,
    league: "National",
    division: "East",
    description: "The Amazin' Mets play in Citi Field, a stunning homage to Ebbets Field, home to Flushing's baseball faithful.",
  },
  {
    id: "phi",
    slug: "philadelphia-phillies",
    name: "Philadelphia Phillies",
    city: "Philadelphia",
    shortName: "PHI",
    primaryColor: "#e81828",
    accentColor: "#002d72",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/phi/800/450",
    stadium: "Citizens Bank Park",
    stadiumCapacity: 42792,
    founded: 1883,
    championships: 2,
    league: "National",
    division: "East",
    description: "Citizens Bank Park has hosted two World Series since opening in 2004, home to some of sport's most passionate fans.",
  },
  {
    id: "was",
    slug: "washington-nationals",
    name: "Washington Nationals",
    city: "Washington",
    shortName: "WAS",
    primaryColor: "#ab0003",
    accentColor: "#14225a",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/bal/800/450",
    stadium: "Nationals Park",
    stadiumCapacity: 41339,
    founded: 1969,
    championships: 1,
    league: "National",
    division: "East",
    description: "The 2019 World Series champions play along the Anacostia River in a park celebrated for its sight lines and fan amenities.",
  },
  // ── National League Central ──
  {
    id: "chc",
    slug: "chicago-cubs",
    name: "Chicago Cubs",
    city: "Chicago",
    shortName: "CHC",
    primaryColor: "#0e3386",
    accentColor: "#cc3433",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/chc/800/450",
    stadium: "Wrigley Field",
    stadiumCapacity: 41649,
    founded: 1876,
    championships: 3,
    league: "National",
    division: "Central",
    description: "The Friendly Confines of Wrigley Field, opened in 1914, is one of baseball's most iconic and beloved ballparks.",
  },
  {
    id: "cin",
    slug: "cincinnati-reds",
    name: "Cincinnati Reds",
    city: "Cincinnati",
    shortName: "CIN",
    primaryColor: "#c6011f",
    accentColor: "#000000",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/nyy/800/450",
    stadium: "Great American Ball Park",
    stadiumCapacity: 42319,
    founded: 1882,
    championships: 5,
    league: "National",
    division: "Central",
    description: "The Reds were baseball's first professional team in 1869. Great American Ball Park sits on the Ohio River waterfront.",
  },
  {
    id: "mil",
    slug: "milwaukee-brewers",
    name: "Milwaukee Brewers",
    city: "Milwaukee",
    shortName: "MIL",
    primaryColor: "#12284b",
    accentColor: "#ffc52f",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/det/800/450",
    stadium: "American Family Field",
    stadiumCapacity: 41900,
    founded: 1969,
    championships: 0,
    league: "National",
    division: "Central",
    description: "American Family Field's retractable roof and legendary racing sausages make the Brewers' park one of MLB's most entertaining.",
  },
  {
    id: "pit",
    slug: "pittsburgh-pirates",
    name: "Pittsburgh Pirates",
    city: "Pittsburgh",
    shortName: "PIT",
    primaryColor: "#27251f",
    accentColor: "#fdb827",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/hou/800/450",
    stadium: "PNC Park",
    stadiumCapacity: 38362,
    founded: 1882,
    championships: 5,
    league: "National",
    division: "Central",
    description: "PNC Park consistently wins best ballpark surveys, featuring stunning views of the Roberto Clemente Bridge and Pittsburgh skyline.",
  },
  {
    id: "stl",
    slug: "st-louis-cardinals",
    name: "St. Louis Cardinals",
    city: "St. Louis",
    shortName: "STL",
    primaryColor: "#c41e3a",
    accentColor: "#0c2340",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/cle/800/450",
    stadium: "Busch Stadium",
    stadiumCapacity: 45538,
    founded: 1882,
    championships: 11,
    league: "National",
    division: "Central",
    description: "St. Louis is baseball's most passionate fan city, with 11 World Series titles making the Cardinals the NL's most storied team.",
  },
  // ── National League West ──
  {
    id: "ari",
    slug: "arizona-diamondbacks",
    name: "Arizona Diamondbacks",
    city: "Phoenix",
    shortName: "ARI",
    primaryColor: "#a71930",
    accentColor: "#e3d4ad",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/mia/800/450",
    stadium: "Chase Field",
    stadiumCapacity: 48405,
    founded: 1998,
    championships: 1,
    league: "National",
    division: "West",
    description: "Chase Field's retractable roof and swimming pool in right-center make it one of the most unique venues in sports.",
  },
  {
    id: "col",
    slug: "colorado-rockies",
    name: "Colorado Rockies",
    city: "Denver",
    shortName: "COL",
    primaryColor: "#33006f",
    accentColor: "#c4ced4",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/sea/800/450",
    stadium: "Coors Field",
    stadiumCapacity: 50398,
    founded: 1993,
    championships: 0,
    league: "National",
    division: "West",
    description: "At 5,280 feet, Coors Field plays at the highest altitude in MLB. The thin air means hitters can expect more home runs here.",
  },
  {
    id: "lad",
    slug: "los-angeles-dodgers",
    name: "Los Angeles Dodgers",
    city: "Los Angeles",
    shortName: "LAD",
    primaryColor: "#005a9c",
    accentColor: "#ef3e42",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/tex/800/450",
    stadium: "Dodger Stadium",
    stadiumCapacity: 56000,
    founded: 1883,
    championships: 8,
    league: "National",
    division: "West",
    description: "Dodger Stadium is the third-oldest ballpark in MLB and the crown jewel of Los Angeles sports, with spectacular hillside views.",
  },
  {
    id: "sd",
    slug: "san-diego-padres",
    name: "San Diego Padres",
    city: "San Diego",
    shortName: "SD",
    primaryColor: "#2f241d",
    accentColor: "#ffc425",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/laa/800/450",
    stadium: "Petco Park",
    stadiumCapacity: 42445,
    founded: 1969,
    championships: 0,
    league: "National",
    division: "West",
    description: "Petco Park seamlessly blends San Diego's historic Western Metal Supply building into its left-field corner, creating a unique aesthetic.",
  },
  {
    id: "sf",
    slug: "san-francisco-giants",
    name: "San Francisco Giants",
    city: "San Francisco",
    shortName: "SF",
    primaryColor: "#27251f",
    accentColor: "#fd5a1e",
    textColor: "#ffffff",
    stadiumImage: "https://picsum.photos/seed/sf/800/450",
    stadium: "Oracle Park",
    stadiumCapacity: 41915,
    founded: 1883,
    championships: 8,
    league: "National",
    division: "West",
    description: "Oracle Park sits on the San Francisco Bay, where McCovey Cove awaits the splash hits of Giants legends.",
  },
];

/* ─── Categories ─── */
export const TEAM_CATEGORIES: TeamCategory[] = [
  {
    id: "all",
    label: "All Teams",
    subtitle: "30 Teams",
    icon: "⚾",
    filter: () => true,
  },
  {
    id: "al",
    label: "American League",
    subtitle: "15 Teams",
    icon: "🏆",
    filter: (t) => t.league === "American",
  },
  {
    id: "nl",
    label: "National League",
    subtitle: "15 Teams",
    icon: "🏅",
    filter: (t) => t.league === "National",
  },
  {
    id: "east",
    label: "East Division",
    subtitle: "10 Teams",
    icon: "E",
    filter: (t) => t.division === "East",
  },
  {
    id: "central",
    label: "Central Division",
    subtitle: "10 Teams",
    icon: "C",
    filter: (t) => t.division === "Central",
  },
  {
    id: "west",
    label: "West Division",
    subtitle: "10 Teams",
    icon: "W",
    filter: (t) => t.division === "West",
  },
  {
    id: "expansion",
    label: "Expansion Teams",
    subtitle: "4 Teams",
    icon: "★",
    filter: (t) => t.founded >= 1990,
  },
  {
    id: "original",
    label: "Original Franchises",
    subtitle: "8 Teams",
    icon: "🏛",
    filter: (t) => t.founded <= 1901,
  },
  {
    id: "champions",
    label: "Championship Winners",
    subtitle: "12 Teams",
    icon: "🥇",
    filter: (t) => t.championships > 0,
  },
  {
    id: "hof",
    label: "Hall of Fame Teams",
    subtitle: "20 Teams",
    icon: "🏛",
    filter: (t) => t.championships >= 1 || t.founded <= 1920,
  },
];

/* ─── Timeline ─── */
export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    year: "1871",
    title: "National Association of Professional Base Ball Players formed",
    description: "",
  },
  {
    year: "1901",
    title: "American League Established",
    description: "",
  },
  {
    year: "1903",
    title: "First Modern World Series",
    description: "",
  },
  {
    year: "1947",
    title: "Jackie Robinson Breaks the Color Barrier",
    description: "",
  },
  {
    year: "1961",
    title: "Expansion Era Begins",
    description: "",
  },
  {
    year: "1998",
    title: "Arizona Diamondbacks Join MLB",
    description: "",
  },
  {
    year: "2023",
    title: "Latest League Expansion Updates",
    description: "",
  },
];

/* ─── Quick Facts ─── */
export const QUICK_FACTS: QuickFact[] = [
  { icon: "⚾", value: "30", label: "Teams" },
  { icon: "🏆", value: "2", label: "Leagues" },
  { icon: "📍", value: "6", label: "Divisions" },
  { icon: "📅", value: "1871", label: "Oldest Franchise (Red Stockings)" },
  { icon: "🆕", value: "1998", label: "Newest Franchise (D-backs)" },
  { icon: "🥇", value: "27", label: "Most Championships (Yankees)" },
  { icon: "🏟", value: "105,339", label: "Largest Stadium (Dodger Stadium)" },
  { icon: "🏟", value: "11,000", label: "Smallest Stadium (Tropicana Field)" },
  { icon: "📈", value: "86", label: "Longest Active Streak (Braves)" },
  { icon: "💰", value: "$6.3B", label: "Most Valuable Franchise (Yankees)" },
];

/* ─── Featured Teams (top 6 for carousel) ─── */
export const FEATURED_TEAM_IDS = ["nyy", "lad", "bos", "chc", "atl", "hou"];

/* ─── Service Functions ─── */

export async function getTeams(): Promise<MLBTeam[]> {
  return ALL_TEAMS;
}

export async function getTeam(id: string): Promise<MLBTeam | undefined> {
  return ALL_TEAMS.find((t) => t.id === id || t.slug === id);
}

export function searchTeams(
  teams: MLBTeam[],
  query: string,
  league?: "All" | "American" | "National",
  division?: "All" | "East" | "Central" | "West",
  categoryId?: string
): MLBTeam[] {
  const q = query.toLowerCase().trim();

  return teams.filter((team) => {
    const matchesSearch =
      !q ||
      team.name.toLowerCase().includes(q) ||
      team.city.toLowerCase().includes(q) ||
      team.stadium.toLowerCase().includes(q) ||
      team.league.toLowerCase().includes(q) ||
      team.division.toLowerCase().includes(q) ||
      team.shortName.toLowerCase().includes(q);

    const matchesLeague = !league || league === "All" || team.league === league;
    const matchesDivision = !division || division === "All" || team.division === division;

    const category = TEAM_CATEGORIES.find((c) => c.id === categoryId);
    const matchesCategory = !category || category.id === "all" || category.filter(team);

    return matchesSearch && matchesLeague && matchesDivision && matchesCategory;
  });
}

export async function getFeaturedTeams(): Promise<MLBTeam[]> {
  return ALL_TEAMS.filter((t) => FEATURED_TEAM_IDS.includes(t.id));
}

export async function getCategories(): Promise<TeamCategory[]> {
  return TEAM_CATEGORIES;
}

export async function getTimeline(): Promise<TimelineEvent[]> {
  return TIMELINE_EVENTS;
}

export async function getQuickFacts(): Promise<QuickFact[]> {
  return QUICK_FACTS;
}
